//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gladiator")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub attack: i32,
    pub defence: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attack_types_gladiators::Entity")]
    AttackTypesGladiators,
}

impl Related<super::attack_types_gladiators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttackTypesGladiators.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
