//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::attack_type::Entity as AttackType;
pub use super::attack_types_gladiators::Entity as AttackTypesGladiators;
pub use super::gladiator::Entity as Gladiator;
